import React, { useState } from 'react';
import { CaseFile, CaseTask, TaskType, ActivityLog, MedicalProvider, ERVisit } from '../types';
import {
  getWorkflowProgress,
  WorkflowStageProgress,
  WorkflowCheckItem,
  WorkflowItemAction,
} from '../services/workflowEngine';
import { WorkflowActionModal, WorkflowActionType } from './WorkflowActionModal';

interface WorkflowKanbanProps {
  caseData: CaseFile;
  onUpdateCase: (c: CaseFile) => void;
}

interface ActiveAction {
  type: WorkflowActionType;
  provider?: MedicalProvider;
  erVisit?: ERVisit;
}

const STAGE_COLORS: Record<WorkflowStageProgress['status'], { header: string; dot: string; border: string }> = {
  complete: { header: 'bg-emerald-50 border-emerald-200', dot: 'bg-emerald-500', border: 'border-emerald-200' },
  active: { header: 'bg-blue-50 border-blue-200', dot: 'bg-blue-500', border: 'border-blue-200' },
  pending: { header: 'bg-slate-50 border-slate-200', dot: 'bg-slate-300', border: 'border-slate-200' },
  blocked: { header: 'bg-slate-50 border-slate-100', dot: 'bg-slate-200', border: 'border-slate-100' },
};

const ACTION_LABELS: Record<WorkflowItemAction, string> = {
  lor_defendant: 'Generate',
  lor_client_ins: 'Generate',
  crash_report: 'FOIA',
  hipaa: 'Form',
  bill_request: 'Request',
  records_request: 'Request',
  er_bill_request: 'Request',
  er_records_request: 'Request',
};

export const WorkflowKanban: React.FC<WorkflowKanbanProps> = ({ caseData, onUpdateCase }) => {
  const [activeAction, setActiveAction] = useState<ActiveAction | null>(null);
  const [completingId, setCompletingId] = useState<string | null>(null);

  const stages = getWorkflowProgress(caseData);

  const handleComplete = (item: WorkflowCheckItem) => {
    if (item.done || !item.taskType) return;
    setCompletingId(item.id);
    setTimeout(() => {
      const existing = (caseData.tasks || []).find(t => t.type === item.taskType && t.status !== 'completed');
      let updated: CaseFile;
      if (existing) {
        updated = {
          ...caseData,
          tasks: (caseData.tasks || []).map(t =>
            t.id === existing.id
              ? { ...t, status: 'completed' as const, completedDate: new Date().toISOString() }
              : t
          ),
        };
      } else {
        const newTask: CaseTask = {
          id: `wf-done-${item.taskType}-${Date.now()}`,
          caseId: caseData.id,
          title: `${(item.taskType as string).replace(/_/g, ' ')} completed`,
          type: item.taskType,
          status: 'completed',
          dueDate: new Date().toISOString().split('T')[0],
          completedDate: new Date().toISOString(),
          priority: 'medium',
          recurrence: 'one-time',
          createdAt: new Date().toISOString(),
          autoGenerated: true,
        };
        updated = { ...caseData, tasks: [...(caseData.tasks || []), newTask] };
      }
      onUpdateCase(updated);
      setCompletingId(null);
    }, 250);
  };

  const openAction = (action: WorkflowItemAction, providerId?: string, erVisitId?: string) => {
    const provider = providerId ? (caseData.medicalProviders || []).find(p => p.id === providerId) : undefined;
    const erVisit = erVisitId ? (caseData.erVisits || []).find(v => v.id === erVisitId) : undefined;
    setActiveAction({ type: action as WorkflowActionType, provider, erVisit });
  };

  return (
    <div className="space-y-4">
      <div className="overflow-x-auto pb-4 -mx-2 px-2">
        <div className="flex gap-4" style={{ minWidth: stages.length * 260 }}>
          {stages.map(stage => {
            const colors = STAGE_COLORS[stage.status];
            const doneCount = stage.items.filter(i => i.done).length;
            const todoItems = stage.items.filter(i => !i.done);
            const doneItems = stage.items.filter(i => i.done);

            return (
              <div
                key={stage.stage}
                className={`flex-shrink-0 w-[260px] bg-white rounded-xl border ${colors.border} flex flex-col max-h-[70vh]`}
              >
                <div className={`px-4 py-3 rounded-t-xl border-b ${colors.header}`}>
                  <div className="flex items-center gap-2 mb-1">
                    <div className={`w-2.5 h-2.5 rounded-full ${colors.dot}`} />
                    <h4 className="font-bold text-sm text-slate-800 truncate flex-1">{stage.label}</h4>
                    {(() => {
                      const missing = stage.infoFields?.filter(f => f.status === 'missing') || [];
                      return missing.length > 0 && stage.status !== 'complete' ? (
                        <span className="text-[9px] font-bold bg-rose-50 text-rose-600 px-1.5 py-0.5 rounded-full flex-shrink-0">
                          {missing.length} missing
                        </span>
                      ) : null;
                    })()}
                  </div>
                  <div className="flex items-center justify-between">
                    <p className="text-[10px] text-slate-500 leading-tight truncate flex-1 mr-2">{stage.description}</p>
                    <span className={`text-[10px] font-bold px-1.5 py-0.5 rounded-full flex-shrink-0 ${
                      stage.status === 'complete'
                        ? 'bg-emerald-100 text-emerald-700'
                        : stage.status === 'active'
                        ? 'bg-blue-100 text-blue-700'
                        : 'bg-slate-100 text-slate-500'
                    }`}>
                      {doneCount}/{stage.items.length}
                    </span>
                  </div>
                  {stage.contacts && stage.contacts.length > 0 && stage.status !== 'complete' && (
                    <div className="flex items-center gap-1.5 mt-2 pt-2 border-t border-slate-200/50">
                      <div className="flex -space-x-1">
                        {stage.contacts.slice(0, 3).map((ct, i) => (
                          <div key={i} className="w-5 h-5 rounded-full bg-white border border-slate-200 flex items-center justify-center" title={ct.name}>
                            <span className="text-[7px] font-bold text-slate-600">
                              {ct.name.split(' ').map(w => w[0]).join('').substring(0, 2).toUpperCase()}
                            </span>
                          </div>
                        ))}
                      </div>
                      <span className="text-[9px] text-slate-500 truncate">
                        {stage.contacts.map(ct => ct.name.split(' ')[0]).join(', ')}
                      </span>
                    </div>
                  )}
                </div>

                <div className="flex-1 overflow-y-auto p-2 space-y-1.5">
                  {todoItems.map(item => (
                    <KanbanCard
                      key={item.id}
                      item={item}
                      completing={completingId === item.id}
                      onComplete={() => handleComplete(item)}
                      onAction={item.action ? () => openAction(item.action!, item.providerId, item.erVisitId) : undefined}
                      actionLabel={item.action ? ACTION_LABELS[item.action] : undefined}
                    />
                  ))}

                  {doneItems.length > 0 && todoItems.length > 0 && (
                    <div className="flex items-center gap-2 py-1.5 px-1">
                      <div className="flex-1 h-px bg-slate-100" />
                      <span className="text-[9px] text-slate-400 font-medium uppercase tracking-wide">Completed</span>
                      <div className="flex-1 h-px bg-slate-100" />
                    </div>
                  )}

                  {doneItems.map(item => (
                    <KanbanCard
                      key={item.id}
                      item={item}
                      completing={false}
                      onComplete={() => {}}
                    />
                  ))}

                  {stage.items.length === 0 && (
                    <div className="text-center py-6 text-xs text-slate-400">No items</div>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {activeAction && (
        <WorkflowActionModal
          isOpen={true}
          onClose={() => setActiveAction(null)}
          caseData={caseData}
          actionType={activeAction.type}
          provider={activeAction.provider}
          erVisit={activeAction.erVisit}
          onUpdateCase={(updated) => {
            onUpdateCase(updated);
            setActiveAction(null);
          }}
        />
      )}
    </div>
  );
};

interface KanbanCardProps {
  item: WorkflowCheckItem;
  completing: boolean;
  onComplete: () => void;
  onAction?: () => void;
  actionLabel?: string;
}

const KanbanCard: React.FC<KanbanCardProps> = ({ item, completing, onComplete, onAction, actionLabel }) => {
  if (item.done) {
    return (
      <div className="bg-slate-50 rounded-lg px-3 py-2 border border-slate-100 opacity-60">
        <div className="flex items-start gap-2">
          <div className="w-4 h-4 rounded-full bg-emerald-500 flex items-center justify-center flex-shrink-0 mt-0.5">
            <svg className="w-2.5 h-2.5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
            </svg>
          </div>
          <span className="text-xs text-slate-400 line-through leading-tight">{item.label}</span>
        </div>
      </div>
    );
  }

  return (
    <div className={`rounded-lg px-3 py-2.5 border transition-all ${
      item.urgent
        ? 'bg-amber-50 border-amber-200 shadow-sm shadow-amber-100'
        : 'bg-white border-slate-150 hover:border-blue-200 hover:shadow-sm'
    }`}>
      <div className="flex items-start gap-2">
        <button
          onClick={onComplete}
          disabled={!item.taskType}
          className={`w-4 h-4 rounded-full border-2 flex-shrink-0 mt-0.5 transition-all ${
            completing
              ? 'border-emerald-400 bg-emerald-100'
              : item.urgent
              ? 'border-amber-400 hover:bg-amber-100'
              : item.taskType
              ? 'border-slate-300 hover:border-blue-400 hover:bg-blue-50'
              : 'border-slate-200'
          }`}
        />
        <div className="flex-1 min-w-0">
          <p className="text-xs font-medium text-slate-800 leading-tight">{item.label}</p>
          {item.detail && (
            <p className={`text-[10px] mt-0.5 ${item.urgent ? 'text-amber-600 font-medium' : 'text-slate-400'}`}>
              {item.detail}
            </p>
          )}
          {item.contact && (
            <p className="text-[9px] text-slate-400 mt-0.5 truncate">
              {item.contact.name}{item.contact.phone ? ` - ${item.contact.phone}` : ''}
            </p>
          )}
        </div>
      </div>

      {item.infoNeeded && item.infoNeeded.length > 0 && (
        <div className="flex flex-wrap gap-1 mt-1.5 ml-6">
          {item.infoNeeded.slice(0, 3).map((info, i) => (
            <span key={i} className="text-[8px] bg-rose-50 text-rose-500 border border-rose-100 px-1 py-0.5 rounded font-medium">
              {info}
            </span>
          ))}
          {item.infoNeeded.length > 3 && (
            <span className="text-[8px] text-slate-400">+{item.infoNeeded.length - 3}</span>
          )}
        </div>
      )}

      <div className="flex items-center gap-1.5 mt-2">
        {item.urgent && (
          <span className="text-[9px] font-bold bg-amber-100 text-amber-700 px-1.5 py-0.5 rounded uppercase">
            Follow Up
          </span>
        )}
        {onAction && actionLabel && (
          <button
            onClick={e => { e.stopPropagation(); onAction(); }}
            className="ml-auto text-[10px] font-semibold text-blue-600 hover:text-blue-800 bg-blue-50 hover:bg-blue-100 px-2 py-0.5 rounded transition-colors flex items-center gap-1"
          >
            <svg className="w-2.5 h-2.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414A1 1 0 0119 9.414V19a2 2 0 01-2 2z" />
            </svg>
            {actionLabel}
          </button>
        )}
      </div>
    </div>
  );
};
